// Code generated by encore. DO NOT EDIT.

package fees

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

func OpenBill(ctx context.Context, p *OpenBillRequest) (*OpenBillResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*OpenBillResponse)(nil), nil
}

func CloseBill(ctx context.Context, billId string, p *CloseBillRequest) (*CloseBillResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*CloseBillResponse)(nil), nil
}

func SealBill(ctx context.Context, p *SealBillRequest) (*CloseBillResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*CloseBillResponse)(nil), nil
}

func GetBill(ctx context.Context, billId string, p *GetBillRequest) (*GetBillResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*GetBillResponse)(nil), nil
}

func ListBills(ctx context.Context, p *ListBillsRequest) (*ListBillsResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ListBillsResponse)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	OpenBill(ctx context.Context, p *OpenBillRequest) (*OpenBillResponse, error)

	CloseBill(ctx context.Context, billId string, p *CloseBillRequest) (*CloseBillResponse, error)

	SealBill(ctx context.Context, p *SealBillRequest) (*CloseBillResponse, error)

	GetBill(ctx context.Context, billId string, p *GetBillRequest) (*GetBillResponse, error)

	ListBills(ctx context.Context, p *ListBillsRequest) (*ListBillsResponse, error)
}
